### PR TITLE
adds missing microsoft-graph readme

### PR DESCRIPTION
**Pull request by rajadilipkolli**
@yungez @xscript  After #71 is merged this should be merged

### CODE REVIEW

**Comment by ZhijunZhao** [comment]
@rajadilipkolli the change didn't get merged to master. It seems I should have approved this PR first before merging the other PR.

**Comment by rajadilipkolli** [comment]
@ZhijunZhao Since #71 is merged should I resubmit against master?

**Comment by ZhijunZhao** [comment]
@rajadilipkolli you're welcome to do that.

**Comment by rajadilipkolli** [comment]
created #78

**Pull request merged**
